m4_define([AT_PACKAGE_NAME], [fig2dev])
m4_define([AT_PACKAGE_TARNAME], [fig2dev])
m4_define([AT_PACKAGE_VERSION], [3.2.8b])
m4_define([AT_PACKAGE_STRING], [fig2dev 3.2.8b])
m4_define([AT_PACKAGE_BUGREPORT], [thomas.loimer@tuwien.ac.at])
m4_define([AT_PACKAGE_URL], [https://sourceforge.net/projects/mcj])
