#ifndef _FUZZ_CONFIG_H_
#define _FUZZ_CONFIG_H_
//#define DEBUG_MODE
#define GEN_CTL_FD 200
#define GEN_ST_FD 201
#define SHM_ENV_VAR_GENERATOR "SHM_ENV_VAR_GENERATOR"
#define FILE_LENGTH_MAX 1<<22
#define MUTATE_MAX 120000


#endif
