m4_define([AT_PACKAGE_NAME], [xfig])
m4_define([AT_PACKAGE_TARNAME], [xfig])
m4_define([AT_PACKAGE_VERSION], [3.2.8b])
m4_define([AT_PACKAGE_STRING], [xfig 3.2.8b])
m4_define([AT_PACKAGE_BUGREPORT], [thomas.loimer@tuwien.ac.at])
m4_define([AT_PACKAGE_URL], [https://sourceforge.net/projects/mcj/])
